const RUN_FILTER = 'RUN_FILTER'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const SETUP_COMMENTS = 'SETUP_COMMENTS'
const SETUP_POST = 'SETUP_POST'
const UPDATE_COMMENT_VOTES = 'UPDATE_COMMENT_VOTES'
const UPDATE_POST_VOTES = 'UPDATE_POST_VOTES'

export {
  RUN_FILTER,
  LOGIN,
  LOGOUT,
  SETUP_COMMENTS,
  SETUP_POST,
  UPDATE_COMMENT_VOTES,
  UPDATE_POST_VOTES,
}
