const RUN_FILTER = 'RUN_FILTER'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const GET_POST_LIST = 'GET_POST_LIST'
const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
const GET_POST_LIST_ERROR = 'GET_POST_LIST_ERROR'

export {
  RUN_FILTER,
  LOGIN,
  LOGOUT,
  GET_POST_LIST,
  GET_POST_LIST_SUCCESS,
  GET_POST_LIST_ERROR,
}
