const RUN_FILTER = 'RUN_FILTER'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const SETUP_COMMENTS = 'SETUP_COMMENTS'
const SETUP_POST = 'SETUP_POST'
const UPDATE_COMMENT_VOTES = 'UPDATE_COMMENT_VOTES'
const UPDATE_POST_VOTES = 'UPDATE_POST_VOTES'
const ADD_COMMENT = 'ADD_COMMENT'
const COMMENT_CREATE_DIALOG = 'COMMENT_CREATE_DIALOG'
const GET_POST_LIST = 'GET_POST_LIST'
const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
const GET_POST_LIST_ERROR = 'GET_POST_LIST_ERROR'
const SET_SEARCH_STRING = 'SET_SEARCH_STRING'

export {
  RUN_FILTER,
  LOGIN,
  LOGOUT,
  SETUP_COMMENTS,
  SETUP_POST,
  UPDATE_COMMENT_VOTES,
  UPDATE_POST_VOTES,
  ADD_COMMENT,
  COMMENT_CREATE_DIALOG,
  GET_POST_LIST,
  GET_POST_LIST_SUCCESS,
  GET_POST_LIST_ERROR,
  SET_SEARCH_STRING,
}
